default_agent: furnitureagent
agents:
  furnitureagent:
    name: furnitureagent
    entrypoint: agent_runtime.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::132260253285:role/AgentCoreGatewayExecutionRole
      execution_role_auto_create: false
      account: '132260253285'
      region: us-east-1
      ecr_repository: 132260253285.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-furniture-agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: furnitureagent-6hUMr6H0ic
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:132260253285:runtime/furnitureagent-6hUMr6H0ic
      agent_session_id: 5414fabc-656f-403b-ae5e-4d1ff36e015b
    codebuild:
      project_name: bedrock-agentcore-furnitureagent-builder
      execution_role: arn:aws:iam::132260253285:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-011ab68583
      source_bucket: bedrock-agentcore-codebuild-sources-132260253285-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
